language: node_js
node_js:
  - "stable"
dist: focal

before_install:
  - gem install bundler -v 2.4.22 
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: mainlanguage: node_js
node_js:
  - "stable"
dist: focal
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: main

